
name: Auto Fix Errors with OpenAI, Flask/React Integration, and UI Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_and_fix:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python and Node.js
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Python (Flask) dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Flask dependencies

    - name: Install Node.js (React) dependencies
      working-directory: paranoid-ui
      run: |
        npm install  # Install React dependencies

    - name: Run Flask and React apps
      id: run_flask_react
      run: |
        nohup python app.py &  # Flask backend
        nohup npm start --prefix paranoid-ui &  # React frontend
      continue-on-error: true

    - name: Handle errors with OpenAI and Selenium
      if: failure()
      run: |
        echo "Error detected, fixing with OpenAI..."
        python fix_errors.py "${{ secrets.OPENAI_API_KEY }}"  # Script to fix errors
        # After fixing, re-launch Flask/React apps and test
        python fix_errors.py "${{ secrets.OPENAI_API_KEY }}"

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-fixed errors using OpenAI and tested with Selenium"
        git push
      if: failure() || success()
