
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install flake8 black pytest

      - name: Run Flake8 for linting
        run: flake8 . || true  # Ensures linter warnings don't fail the pipeline

      - name: Run Black for formatting check
        run: black --check . || true  # Ensures formatting warnings don't fail the pipeline

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run tests
        run: pytest || true  # Ensures tests run without failing the entire pipeline
