
name: Advanced CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Updated Python version to ensure compatibility

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install flake8 black pylint bandit pytest

      - name: Run Flake8 for linting
        run: flake8 .  # Removed error suppression

      - name: Run Pylint as fallback linter
        run: pylint .  # Removed error suppression

      - name: Run Black for formatting check
        run: black --check .  # Removed error suppression

      - name: Fallback format check (if Black fails)
        run: isort --check-only .  # Removed error suppression

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Run Bandit security checks
        run: bandit -r .  # Removed error suppression

  test:
    runs-on: ubuntu-latest
    needs: [lint, security]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run tests with Pytest
        run: pytest  # Removed error suppression

      - name: Fallback test runner (Nose2)
        run: nose2  # Removed error suppression
