
name: Weekly Health Check

on:
  schedule:
    - cron: "0 12 * * 1"  # Runs every Monday at 12 PM
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  check-health:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: List directory contents for debugging
      run: |
        ls -la  # List all files to ensure health_check.py exists and is accessible

    - name: Run health check
      run: python health_check.py  # Runs the health check script
