
name: Setup Runtime and Auto-Skip APIs

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install expect
      run: |
        sudo apt-get expect

    - name: Run setup_runtime.py and auto-skip any prompt
      run: |
        expect << EOF
        spawn python setup_runtime.py
        expect {
          -re ".*" { send exp_continue ; exp_continue ; exp_continue ; exp_continue ; exp_continue ; exp_continue ; exp_continue }  # Sending "skip" followed by newline
        }
        EOF
